# Generated by Django 2.2.9 on 2020-10-01 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20201001_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['text']},
        ),
    ]
