# Generated by Django 2.2.9 on 2020-10-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20201001_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-text']},
        ),
    ]
